name: API TM LIS Prod Deployment
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  deploy_prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.LS_PROD_SERVER_PVT_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LS_PROD_SERVER_IP }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: >-
          ssh ${{ secrets.LS_SSH_USER }}@${{ secrets.LS_PROD_SERVER_IP }} "cd
          /home/${{ secrets.LS_SSH_USER }} && mkdir -p ${{ vars.PROD_APP_FOLDER }}
          && cd ${{ vars.PROD_APP_FOLDER }} && git init && git fetch ${{
          vars.CUSTOM_SSH_REPO_URL }} main && git checkout FETCH_HEAD && source /home/${{
          secrets.LS_SSH_USER }}/.nvm/nvm.sh && npm install && pm2
          startOrReload ecosystem.config.js && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
